alert('Hallo! Vul deze vragen in!')
var voornaam = prompt('vul je voornaam in');
var achternaam = prompt('vul je achternaam in');
var leeftijd = prompt('vul je leeftijd in');

document.writeln('wat is jou voornaam?:')
document.writeln(voornaam)
document.write('<br>')
document.writeln('wat is jou achternaam?: ')
document.writeln(achternaam)
document.write('<br>') 
document.writeln('wat is jou leeftijd?: ')
document.writeln(leeftijd)